### ISSUE TITLE
Rename Attributes to AttributesDescription

### ISSUE THREAD

**Issue by MikeHopcroft** [MikeHopcroft/PrixFixe#14]
Might want a name that is not so similar to `AttributeDescription` (see issue #5).  Perhaps `AttributesYAML` or `AttributesFile`?

**Comment by KatieProchilo** [comment]
Renaming to AttributesYaml for the reason you mentioned.

**Comment by KatieProchilo** [comment]
Closed with https://github.com/MikeHopcroft/PrixFixe/commit/3d01050d06d14b7e9172d743b53a608a95c4074b.
