### ISSUE TITLE
Consider where short-order's Order and LineItem class should live

### ISSUE THREAD

**Issue by KatieProchilo** [MikeHopcroft/PrixFixe#28]
We should discuss where short-order's ```Order``` and ```LineItem``` class should live. They are currently in short-order and should be moved over to PrixFixe.

**Comment by KatieProchilo** [comment]
@MikeHopcroft did I get ```Space``` and ```Line`` correct? I didn't notice classes by either name in short-order.

**Comment by MikeHopcroft** [comment]
I think it is Order and LineItem.

**Comment by MikeHopcroft** [comment]
Commit 9a2321c7639ce6f7ee26aa7364bcbd25db31b002 brings in TestOrder and TestLineItem. At this point is seems that PrixFixe doesn't need Order and LineItem.
