### ISSUE TITLE
Consider removing AttributeItem.isDefault

### ISSUE THREAD

**Issue by MikeHopcroft** [MikeHopcroft/PrixFixe#3]
Now that genericEntities specify a `defaultKey`, there is no need for the AttributeItem to provide an optioanl `isDefault` field. We should remove this field.

**Comment by KatieProchilo** [comment]
Closed with https://github.com/MikeHopcroft/PrixFixe/commit/2a00505dfbdddbd8e13076384b196d0bcfd55068
