### ISSUE TITLE
Address TODO: comments

### ISSUE THREAD

**Issue by MikeHopcroft** [MikeHopcroft/PrixFixe#31]
This is probably an ongoing task, but let's do the following:

- Remove TODO: comments that are no longer valid (or have already been addressed)
- Open issues for the more architecturally significant TODO: comments

Let's do this as a triage for now. Comments that don't meet one of the two conditions, above, will be left in place.

**Comment by KatieProchilo** [comment]
Anything labeled with "TODO" or "ISSUE" has now been removed or converted to an issue in this repo. Issues 54-68 were born from some TODO comment.

Closed with https://github.com/MikeHopcroft/PrixFixe/commit/bdcad3134f57b58c2c038efca664ceddd67c5024.
