### ISSUE TITLE
Remove "Old" from type names

### ISSUE THREAD

**Issue by drub0y** [MikeHopcroft/PrixFixe#37]
`CartOld`, `ItemInstanceOld`? I assume this was from a point in time when the API was being migrated from `short-order`, but do we plan on cleaning up these names now?

**Comment by drub0y** [comment]
Hmm, I see that there are non-"Old" versions of these names now, they were just being obfuscated by types from another import. That said, we still should consider removing the old `XXXOld` types so they're no longer part of the library any more.

**Comment by drub0y** [comment]
Ok, I see what's so confusing to me right now:`CartUtils` works off the `XXXOld` types and I'm expecting that to work with the new types.

**Comment by MikeHopcroft** [comment]
Done. 8e0a5bc51
