### ISSUE TITLE
No pricing?

### ISSUE THREAD

**Issue by drub0y** [MikeHopcroft/PrixFixe#38]
I was just working on resolving menu items from the catalog and noticed that there is no pricing information available. I would expect to see a `price` property on the `GenericTypedEntity` class for example. Are we still working on bringing in pricing or...?

**Comment by MikeHopcroft** [comment]
We made a design decision that the cart would focus on trees of ItemInstances with keys. The keys allow one to access other properties, like price, weight, tax jurisdiction, markdown status, expiration date, regional availability, etc.
