### ISSUE TITLE
Rename `Matrix` to `Tensor`

### ISSUE THREAD

**Issue by MikeHopcroft** [MikeHopcroft/PrixFixe#4]
We should rename all matrix-related terminology to use the term, `tensor`.

**Comment by MikeHopcroft** [comment]
Also define TID for the tensor id.

**Comment by KatieProchilo** [comment]
Closed with https://github.com/MikeHopcroft/PrixFixe/commit/407795fd2fe8dfa013daaf75c8ffb5be8899e2f4.
