### ISSUE TITLE
Consider renaming AttributeItem to AttributeDescription

### ISSUE THREAD

**Issue by MikeHopcroft** [MikeHopcroft/PrixFixe#5]
In general, perhaps all of the interfaces representing raw YAML should end with `Description`. Instance interfaces might end with `Instance`.

**Comment by KatieProchilo** [comment]
Closed with https://github.com/MikeHopcroft/PrixFixe/commit/e4224bc7c86d76e7ebbe4e1fccd952a4859fcb83.
