### ISSUE TITLE
Investigate code coverage options and badge.

### ISSUE THREAD

**Issue by MikeHopcroft** [MikeHopcroft/PrixFixe#53]

**Comment by KatieProchilo** [comment]
After `travis-ci` tests the build, `coveralls.io` will evaluate the test coverage, and update its badge on README.md.

To locally evaluate tests and test coverage, run:
```
npm run coverage
```

Closed with https://github.com/MikeHopcroft/PrixFixe/commit/f796792cfe7e922a5332d12ec9000700951f2ede.
