### ISSUE TITLE
Define the shape of RuleConfig

### ISSUE THREAD

**Issue by KatieProchilo** [MikeHopcroft/PrixFixe#56]
The current RuleConfig is from a WIP commit. Possibly need to redefine the shape of the rule_checker interface RuleConfig.

**Comment by SpaceKatt** [comment]
https://github.com/MikeHopcroft/PrixFixe/blob/c1efd3c97551435b0db2de0ce9907033dc1a26b2/src/rule_checker/interfaces.ts#L35-L40
