### ISSUE TITLE
Should items be mutually exclusive with themselves?

### ISSUE THREAD

**Issue by KatieProchilo** [MikeHopcroft/PrixFixe#67]
In rule_checker's isMutuallyExclusive(), should items be mutually exclusive with themselves?

**Comment by MikeHopcroft** [comment]
I think that options should be mutually exclusive with themselves.  Consider the following example: `latte with vanilla and vanilla`.

**Comment by MikeHopcroft** [comment]
I have implemented self-exclusion for 

* `getPairwiseMutualExclusionPredicate()`
* `getIncrementalMutualExclusionPredicate()`

in af91cf0dc18badbbe65dca496b70794364d78149.

This has not been implemented for

* `isMutuallyExclusive()`
