### ISSUE TITLE
Remove RuleChecker.isMutuallyExclusive()

### ISSUE THREAD

**Issue by MikeHopcroft** [MikeHopcroft/PrixFixe#75]
Let's discuss whether we will need this API. If we keep it, we need to implement self-exclusivity (#67).

Remove `RuleChecker.isMutuallyExclusive()`. This involves re-implementing its unit tests to one of the following replacements:

* `getPairwiseMutualExclusionPredicate()`
* `getIncrementalMutualExclusionPredicate()()`

It is possible that some tests will no longer be meaningful and can be deleted.

**Comment by SpaceKatt** [comment]
After reviewing `getPairwiseMutualExclusionPredicate()` and `getIncrementalMutualExclusionPredicate()`, it is clear that `isMutuallyExclusive()` is now both redundant and not as flexible.

I'll remove `RuleChecker.isMutuallyExclusive()` and update unit tests to close this issue.
