### ISSUE TITLE
Remove dependency on short-order

### ISSUE THREAD

**Issue by MikeHopcroft** [MikeHopcroft/PrixFixe#8]
prix-fixe should not depend on short-order. Current dependencies include

- Catalog - should be moved into prix-fixe
- IndexableItem - should be moved into prix-fixe
- AttributeToken, EntityToken - used by MatrixEntityBuilder - should be replaced by AID and PID
- AttributeToken, ATTRIBUTE - used by makteAttributeToken in cart.ts - remove this function
- AttributeToken, ATTRIBUTE - used by attribute_info.test.ts - remove after changing MatrixEntityBuilder

**Comment by KatieProchilo** [comment]
All 5 items have been completed. Finished this by uninstalling short-order in https://github.com/MikeHopcroft/PrixFixe/commit/56faacc3c070f65f3c609756c4cdd67e2665c3a4.
