### ISSUE TITLE
Documentation should specify required Node.JS version

### ISSUE THREAD

**Issue by MikeHopcroft** [MikeHopcroft/PrixFixe#80]

**Comment by mytusshar** [comment]
I want to contribute to this issue. This is my first open source issue, little help will be appreciated.
Which file do I need to update with nodejs version, README.d or contributing.md file

**Comment by MikeHopcroft** [comment]
Thanks for your interest! I would put this in the README.md, perhaps in a "getting started" section. I know that it works on v10.15.3, as that is on one of my machines.

It might also be interesting to research how other projects communicate this dependency information. For example, could it be put into the packages.json file somehow.

Let me know if you have more questions.


-Mike



http://www.michaeljhopcroft.com



________________________________

**Comment by liliankasem** [comment]
@mytusshar hello, are you still planning to do this?
